// <auto-generated />
namespace DBWorks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class revertToPrevious : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(revertToPrevious));
        
        string IMigrationMetadata.Id
        {
            get { return "202103101537297_revertToPrevious"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
